### ISSUE TITLE
Xpath box

### ISSUE THREAD

**Issue by arezki1990** [further-reading/scraping-browser#16]
Hello , thanks for this idea , but I was wondering if you could add xpath box to the GUI it's would be perfect

Thnkx

**Comment by further-reading** [comment]
There's already a box for this? The query box is where you enter your xpath/css text, you designate which type using the radio button.

**Comment by arezki1990** [comment]
Thanks for your reply , just update the documentation images

**Comment by further-reading** [comment]
Ah, I knew I left a step out in my 1.1 update! >.< I'll get that update later this evening.
