### ISSUE TITLE
lxml not supported

### ISSUE THREAD

**Issue by kalidas7337** [further-reading/scraping-browser#24]
### _**Installation fails due to **lxml** with the following errors:**_
Kindly suggest alternatives to run this.

AppData\Local\Temp\xmlXPathInitv9uh0kq8.c(1): fatal error C1083: Cannot open include file: 'libxml/xpath.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

**Comment by further-reading** [comment]
The lxml package can have some compatibility issues on windows, searching the error message should lead to some workarounds to get it to work on your system. I've heard upgrading pip and setuptools can do the trick.

**Comment by further-reading** [comment]
As an update here, I have coincedentially had to troubleshoot this issue this week after updating my enviornment!

There is a SO page [here](https://stackoverflow.com/questions/71152710/failing-to-install-lxml-using-pip) with the answer and more details. What you wanna do is go to [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml) and download the version that matches your enviornent, then run `pip install that_filename` The files are named like `lxml-LXMLVERSION-cpPYTHONVERSION-cpPYTHONVERSION_WINDOWSVERSION.whl`
